### PR TITLE
Ability to log additional debuging information

### PR DESCRIPTION
**Pull request by taz77**
Adds a debugging option to the admin page. If turned on, the module will log successful requests to Mailchimp for debugging purposes. Even if the response is empty, a log entry will be created. The option is switched off by default. Cleanup provided in hook_uninstall.

I also converted one of the files to short array syntax to match the rest of the module since PHP 5.5 is required to run the module.

Some small documentation edits.

### CODE REVIEW

**Comment by Greg-Boggs** [comment]
I tried resolving the conflict on this one, but it's difficult without access to your repo and I can't get the 3way remote merge business to work with PHPStorm. Can you resolve the conflicts on this one when you get a chance?

**Comment by taz77** [comment]
@Greg-Boggs Sorry I did not see this message. I will see if I can get things resolved. I just opened another PR to fix some spacing.

**Comment by taz77** [comment]
I am going to rebase off of #118

**Comment by taz77** [comment]
I am going to mark this OBE because other PRs have introduced better logging. There needs to be some tweaking so the message received from Mailchimp is stored in the log. The current errors are too generic, need to see the full response from Mailchimp in the logs when something goes wrong.

**Pull request closed without merging**
