### PR TITLE
Convert to short arrays

### LINKED ISSUE #117: Mixed bag of short and long array declarations used in module clean up to short arrays
The 7.x code has a mixed bag of short and long array declarations declared throughout the code base. Short arrays save a lot of space and the module already requires PHP 5.5 so lets convert to all short arrays.

### PR DESCRIPTION
**Pull request by taz77**
This PR resolves #117, but it depends on PR #116 to be merged first.

In this PR is converting any remaining long array declarations to short array declarations.

### CODE REVIEW

**Comment by taz77** [comment]
I got to rebase this.

**Comment by torgospizza** [comment]
I was just about to comment :) I'm also going to go through and fix some of my old-style array calls. Heh.. whoopsie!

**Comment by taz77** [comment]
Done! 💯

**Comment by taz77** [comment]
PHPStorm formatter to the rescue!

**Comment by taz77** [comment]
@torgospizza I have PHPStorm code styling setup with Drupal's coding standards. I did this manually. Then I can just reformat my entire project.

**Comment by taz77** [comment]
If you don't have PHPStorm you can use it by download the Early Access Program (EAP). This is a version that comes with a 30-day license and they release a new version of the EAP in less than 30 days that comes with a new license. It's a little trick I've learned using a lot of Jetbrains products. I have a paid license for PHPStorm and IntelliJ.

**Comment by torgospizza** [comment]
I have PHPStorm, and love it. Been using it for a few years now - the code formatting tool is something I haven't explored yet, though. I'll have to dig in!

**Comment by taz77** [comment]
@torgospizza Oh gosh. It's one of the best things about PHPStorm. Have you also used the Git Merge Conflict tool, yes?

**Comment by torgospizza** [comment]
@taz77 I have not :( I've done all my resolutions manually. PHPStorm never "volunteered" any such tool, and now I feel like I've been missing out this whole time! I'll look up some reference material and see if I can't make these part of my regular routine.

**Comment by taz77** [comment]
@torgospizza Go cause a conflict. Then open up PHPStorm and go here: 
screen shot 2018-03-12 at 20 48 24

Honestly the best merge conflict tool I have ever used. I am a Java developer by day, so I use IntelliJ at work. I learn a lot of things from the Java world because IntelliJ is extremely popular.

**Comment by Greg-Boggs** [comment]
https://confluence.jetbrains.com/display/PhpStorm/Drupal+Development+using+PhpStorm

**Pull request merged**
