### PR TITLE
Queue API option for MailChimp API calls

### PR DESCRIPTION
**Pull request by torgospizza**
Work to implement the Queue API for performance.

This branch adds a new option to Queue requests (or not), and when selected, instead of calling the MailChimp API every time something is added/removed to a cart (for example), the request is queued. For performance reasons, this is ideal, because the MailChimp API is quite slow, and without this patch it's possible to have very long delays between clicking "Add to cart" and seeing a response.

### CODE REVIEW

**Comment by torgospizza** [comment]
This will probably need a bit of work, as well as testing.

**Comment by torgospizza** [comment]
Closing for now so that I can do a fresh pull

**Comment by torgospizza** [comment]
Fixed conflict by re-merging with upstream.

**Comment by Greg-Boggs** [comment]
I'm going to merge this is now so we don't get merge conflicts. It should be pretty harmless even if it's got a bug or two because it's off by default.

**Comment by torgospizza** [comment]
Thanks, Greg! Indeed, I wanted to make sure folks didn't accidentally run into issues, so it's disabled by default. 

We've used all of the functionality, minus addCart/addOrder functions - which were the latest ones I added - and so I can attest to the fact that they at least work as expected. The only thing to note, of course, is that the Queue worker function may need updating if the signatures of the other API methods change as well.

Thanks for merging this in, the performance issues were a show-stopper for us without it.

**Comment by Greg-Boggs** [comment]
It has been a wish list feature for us since the start. But, we're still in the make it work mode. I'm adding product recommendation support now which requires: Images, URLs, and inventory count.

**Pull request merged**
